# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f27ffd6d689ee0712ba980a61e7fe0c20fb149d1e9b0f5997ee86d7f414df30007efec69a9c8e300f28d40dbe0a72bfaa9ef8df46f188e0bfd2a4720373e7c1

test:
  secret_key_base: 60c1eb295ce427ba4db6f85577eaaeb83a6799389b499dc106c8ad87ae1901572c943d5a0179c4bb7f2408e45cb0ff09b16aec2ff9d8ef68b12b2eccf7321805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
